---
- name: ensure /var/cache/ansible directory exists
  file:
    path: /var/cache/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download the vagrant deb package
  get_url:
    url: "{{ vagrant_download_url }}"
    dest: /var/cache/ansible/vagrant.deb

- name: ensure vagrant package is installed
  command: dpkg -i /var/cache/ansible/vagrant.deb
  register: install_vagrant
  changed_when: install_vagrant.stdout.startswith("Selecting previously unselected package")
