---
- name: ensure /var/cache/ansible directory exists
  file:
    path: /var/cache/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download the vagrant deb package
  get_url:
    url: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb
    dest: /var/cache/ansible/vagrant_1.6.5_x86_64.deb

- name: ensure vagrant package is installed
  command: dpkg -i /var/cache/ansible/vagrant_1.6.5_x86_64.deb
  register: install_vagrant
  changed_when: install_vagrant.stdout.startswith("Selecting previously unselected package")
